### ISSUE TITLE
 global-colorful-mode doesn't respect colorful-mode-map

### ISSUE THREAD

**Issue by seagle0128** [DevelopmentCool2449/colorful-mode#4] opened 2024-06-26 09:02 UTC
https://github.com/DevelopmentCool2449/colorful-mode/blob/cc94056fea3457f6e40c0c4ac8b9569de9c1f47e/colorful-mode.el#L283-L287

**Comment by DevelopmentCool2449** [comment] 2024-06-27 00:45
Thank you for reporting, please tell me if the issue is now fixed

**Closed by DevelopmentCool2449** 2024-06-27 00:45 UTC
